### PR TITLE
Support for new OSC config

### PR DESCRIPTION
**Pull request by crazyscientist**

### CODE REVIEW

**Comment by der-gabe** [comment]
Looks reasonable enough, but can one find information on this new `osc.config` attribute anywhere?

**Comment by crazyscientist** [comment]
> but can one find information on this new osc.config attribute anywhere?

Once the testsuite failed, I went directly to the sources of osc.

**Comment by der-gabe** [comment]
OK, guess I'll have to do the same myself then...

**Comment by der-gabe** [comment]
Found it. LGTM! :slightly_smiling_face: :+1:

**Pull request merged**
